# Generated by Django 5.0.4 on 2024-04-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Disciplines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.IntegerField(blank=True, null=True, unique=True)),
                ('photo', models.ImageField(upload_to='candidates_photos/')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.discipline')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.candidat')),
            ],
            options={
                'verbose_name_plural': 'Votes',
                'ordering': ['-id'],
            },
        ),
    ]
